# Run 'docker-compose -f docker-compose-development.yml build'
# Run 'docker-compose -f docker-compose-development.yml up'
# check http://localhost:9666/api/flights/next - should be response
# go to client side and run the frontend (flights-app\client\README.md)
version: '2'

services:
  spring_api:
    container_name: spring_api_container
    restart: always
    image: api
    build: ./flightapi
    volumes:
      - ./flightapi:/usr/src/app/flightapi
    ports:
      - "9666:9666"
    env_file:
      - .env

  data:
   container_name: app_data_container
   image: postgres:9.6
   volumes:
     - /home/vadym/postgresql
   command: "true"

  postgres:
   container_name: postgresql_container
   restart: always
   build: ./postgresql
   volumes_from:
     - data
   ports:
     - "5432:5432"
   env_file:
     - .env
